### ISSUE TITLE
Ability to set the current project and filter by that project

### ISSUE THREAD

**Issue by frontalnugity** [codefocus/atom-axosoft#1]

**Comment by codefocus** [comment]
The list of issues can be filtered by project using the fuzzy search box at the top of the pane (to the right of the axosoft logo).

I'll make the purpose of that space a bit clearer (it appears as empty space now) and position it statically, so it stays at the top of the pane after scrolling down.

**Comment by codefocus** [comment]
This is now replaced with a clearer UI: Two dropdowns; One for "Filter" (Axosoft filters) and one for "Project".
