### ISSUE TITLE
Reload projects are returning items for the wrong user

### ISSUE THREAD

**Issue by frontalnugity** [codefocus/atom-axosoft#6]

**Comment by codefocus** [comment]
Do you mean that after reloading the projects, the package shows work items not matching the current filter?

Does the new UI resolve this issue, or does it persist?

**Comment by frontalnugity** [comment]
Looks like the issue has been resolved with one of the most recent updates!

**Comment by codefocus** [comment]
Yay!
Thanks for this btw, it helps a lot :)
