### ISSUE TITLE
Fuzzy search functionality ui is not obvious

### ISSUE THREAD

**Issue by frontalnugity** [codefocus/atom-axosoft#7]
It isn't clear to teh user a search exists by the axo logo until you accidentally mouse into that area or it is pointed out by a colleague :)

![image](https://user-images.githubusercontent.com/12880595/34241964-ca33bcee-e5cd-11e7-8c49-86edd4200d17.png)

**Comment by codefocus** [comment]
This unclear UI is now replaced by two filter dropdowns:
- `Filter` and
- `Project`
